#!/usr/bin/sh

while read file
do
    case "$1" in
    "w") 
         wallpaperdir="/home/pwrhs/wallpapers/"
         xwallpaper --zoom "$file"
         mv "$wallpaperdir"/current/* "$wallpaperdir"/all
         mv "$file" "$wallpaperdir"/current
         ;;
    esac
done
